### ISSUE TITLE
deFanging Patterns issue

### ISSUE THREAD

**Issue by infosectester** [ioc-fang/ioc_fanger#10]
I am attempting to add and additional pattern to the defang.json.

`{
        "find": "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b",
        "replace": "redacted@redacted.com"
  }, `
I would like to remove any email address in the url and replace it with redacted@redacted.com

My complete file looks like this

`
[
    {
        "find": "\\S(\\.)\\S",
        "replace": "[.]"
    },
    {
        "find": "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b",
        "replace": "redacted@redacted.com"
    }, 
    {
        "find": "http",
        "replace": "hxxp"
    }
]
`
When I attempt to run deFang I get the following error...

#defang http://google.com/index.php?johndoe@gmail.com
Traceback (most recent call last):
  File "/usr/local/bin/defang", line 7, in <module>
    from ioc_fanger.ioc_fanger import cli_defang
  File "/usr/local/lib/python2.7/dist-packages/ioc_fanger/__init__.py", line 4, in <module>
    from .ioc_fanger import fang, defang
  File "/usr/local/lib/python2.7/dist-packages/ioc_fanger/ioc_fanger.py", line 23, in <module>
    defanging_mappings = _get_data_from_file(DEFANG_DATA_PATH)
  File "/usr/local/lib/python2.7/dist-packages/ioc_fanger/ioc_fanger.py", line 18, in _get_data_from_file
    return json.loads(f.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 7 column 52 (char 128)

Any help would be greatly appreciated.

**Comment by infosectester** [comment]
So I was able to find a work around... 

[
    {
        "find": "=[a-zA-Z0-9]{3,40}@(DOMAIN|DOMAIN).com",
        "replace": "redacted@redacted"
    },
    {
        "find": "http",
        "replace": "hxxp"
    },
    {
        "find": "\\S(\\.)\\S",
        "replace": "[.]"
    }
]

**Comment by fhightower** [comment]
The problem with the first `find` regex you were trying to use (`\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b`) is that the `\` escape characters need to be replaced with two backslashes. A working regex would look like: `\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}\\b`.

A valid defang.json would look something like:

```json
[
    {
        "find": "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}\\b",
        "replace": "redacted@redacted.com"
    },
    {
        "find": "\\S(\\.)\\S",
        "replace": "[.]"
    },
    {
        "find": "http",
        "replace": "hXXp"
    }
]
```

Even this correction won't do what you want it to do, so you also need to change the `find` regex to capture a the email address as a group by putting parenthesis around the part of the regex that matches the email address:

`\\b([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6})\\b`

So a final, working defang.json that does what you need it to do would be:

```json
[
    {
        "find": "\\b([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6})\\b",
        "replace": "redacted@redacted.com"
    },
    {
        "find": "\\S(\\.)\\S",
        "replace": "[.]"
    },
    {
        "find": "http",
        "replace": "hXXp"
    }
]
```
